#
# MAINTAINER        Songwen Wu  <wusongwen@126.com>
# DOCKER-VERSION    1.12.1
# mysql version:    5.6.33
# Dockerizing mysql: Dockerfile for building soonway/mysql:5.6.33 images
#

FROM mysql:5.6.33

MAINTAINER  Songwen Wu  <wusongwen@126.com>

#set Timezone
ENV TZ "Asia/Shanghai"

EXPOSE 3306
CMD ["mysqld"]
